### ISSUE TITLE
Incorrect response when a release log is empty

### ISSUE THREAD

**Issue by tevanoff** [heroku/busl#163]
When an app has a release log but it is empty, the response from `release-output.h.c` has a status code of 200. However, since it is a SSE stream, this means there is possibly more data so clients will keep trying to reconnect. If the log is empty, a response of 204 would be better because it would let the client know that there is no data to be had.

This is currently an open issue in Dashboard because we don't have a good way of determining when a release log is in fact empty.

cc @ojacobson

**Comment by dmathieu** [comment]
Todd,

Do you have a specific build output showing this?

We already check for [empty content](https://github.com/heroku/busl/blob/master/broker/io.go#L263), and [send an error](https://github.com/heroku/busl/blob/master/server/middleware.go#L161) when we get one, which [becomes a 204](https://github.com/heroku/busl/blob/master/server/errors.go#L45).

I've [opened a PR](https://github.com/heroku/busl/pull/164) adding a test for this.
This will only happen if the stream if closed though. If it isn't, we expect data could still come, and can't send a 204 right away.

**Comment by dmathieu** [comment]
Fixed in #164.
