### ISSUE TITLE
Long output lines may break relaying?

### ISSUE THREAD

**Issue by ojacobson** [heroku/busl#64]
See [this ticket](https://support.heroku.com/tickets/338798?t=1456608124).

My theory is that the very-long lines produced by Webpack's progress output (which is the usual `\r60%\r61%\r62%…` sequence, where each progress step overwrites the start of the line) are causing trouble with busltee.

**Comment by dmathieu** [comment]
We were unable to reproduce this issue, and digging further showed that the ticket's issue wasn't due to busl.

[card](https://heroku.clubhouse.io/story/2432/support-long-lines-in-busl)
