### ISSUE TITLE
Allow Client to Delete Streams

### ISSUE THREAD

**Issue by naaman** [heroku/busl#8]
If a client subscribes to a stream, the publisher may wish to cancel the stream without publishing any data. A `DELETE` should close any connected subscribers.

**Comment by cyx** [comment]
Had some discussion about this. Do you have any input as to which part in the stack should execute the ensure-DELETE pattern?

**Comment by naaman** [comment]
IIRC, this was a short-circuiting mechanism rather than an assurance. I can't remember the use case any more, though, so feel free to close unless you have one.
